services:
  ace-step15:
    container_name: ace-step15
    image: edp1096/ace-step-spark:1.5-arm64
    ports:
    - 7860:7860
    - 8001:8001
    volumes:
      - "/home/edp1096/workspace/models:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    # tty: true
    command: /bin/bash -c "cd ~ && ./run.sh && /bin/bash"