services:
  pytorch-base:
    container_name: pytorch-base
    image: nvcr.io/nvidia/pytorch:26.01-py3
    ports:
    - 7860:7860
    - 8001:8001
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    # volumes:
    #   - "/home/edp1096/workspace/models:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true